defmodule Day07Test do
  use ExUnit.Case, async: true

  @example_input ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

  test "part1 example" do
    assert Day07.part1(@example_input) == 21
  end

  test "part2 example" do
    assert Day07.part2(@example_input) == 10000
  end
end
